name: ci

on: [push]

jobs:
  docs:
    runs-on: ubuntu-latest
    name: generate vimdoc from readme
    steps:
      - uses: actions/checkout@v4
      - uses: kdheepak/panvimdoc@main
        with:
          vimdoc: winresize.nvim
          version: "Neovim >= 0.10.0"
          demojify: true
      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore(build): auto-generate vimdoc"
          commit_user_name: "github-actions[bot]"
          commit_user_emails: "github-actions[bot]@user.noreply.github.com"
          commit_author: "github-actions[bot] <github-actions[bot]@user.noreply.github.com>"
